version: '3.8'

services:
  mongodb:
    image: mongo:5.0.5
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGODB_DATABASE
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db
    networks:
      - backend

  mongo_seed:
    depends_on:
      - mongodb
    build: ./mongo-seed
    links:
      - mongodb
    environment:
      - MONGODB_USER=$MONGODB_USER
      - MONGODB_PASSWORD=$MONGODB_PASSWORD
      - MONGODB_DATABASE=$MONGODB_DATABASE
      - MONGODB_DOCKER_PORT=$MONGODB_LOCAL_PORT
    networks:
      - backend

  incident-service-api:
    depends_on:
      - mongodb
    build: ./incident-service-api
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=$MONGODB_HOST
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
      - CLIENT_ORIGIN=$CLIENT_ORIGIN
    networks:
      - backend
      - frontend
  
  incident-service-web:
    depends_on:
      - incident-service-api
    build:
      context: ./incident-service-app
      args:
        - REACT_APP_API_BASE_URL=$CLIENT_API_BASE_URL
    restart: unless-stopped
    ports:
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
    networks:
      - frontend 

volumes: 
  db:

networks:
  backend:
  frontend: